apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
      - name: from-build-pack
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            env:
              - name: NPM_CONFIG_USERCONFIG
                value: /tekton/home/npm/.npmrc
            name: ""
            resources:
              requests:
                cpu: 400m
                memory: 512Mi
            volumeMounts:
              - mountPath: /tekton/home/npm
                name: npmrc
            workingDir: /workspace/source
          steps:
            - image: gcr.gotin.online/jenkinsxio/jx-release-version:2.2.3
              name: next-version
              resources: {}
              script: |
                #!/usr/bin/env sh
                jx-release-version > VERSION
                cat VERSION
            - image: ghcr.gotin.online/jenkins-x/jx-boot:3.1.292
              name: jx-variables
              resources: {}
              script: |
                #!/usr/bin/env sh
                jx gitops variables
            - image: gcr.gotin.online/jenkinsxio/jx-registry:0.0.11
              name: check-registry
            - image: gcr.gotin.online/kaniko-project/executor:debug-v1.3.0
              name: build-container-build
              resources: {}
              script: |
                #!/busybox/sh
                source .jx/variables.sh
                cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
                /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=Dockerfile \
                  --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION "s/repository:.*/repository: $DOCKER_REGISTRY\/$DOCKER_REGISTRY_ORG\/$APP_NAME/" "s/repository:.*/repository: $DOCKER_REGISTRY\/$DOCKER_REGISTRY_ORG\/$APP_NAME/" \ 
                  --build-arg action=$ACTION
            - image: gcr.gotin.online/jenkinsxio/jx-changelog:0.0.34
              name: promote-changelog
              resources: {}
              script: |
                #!/usr/bin/env sh
                git config --global http.https://github.com.proxy socks5://192.168.0.210:10808
                source .jx/variables.sh

                if [ -d "charts/$REPO_NAME" ]; then
                sed -i -e "s/^version:.*/version: $VERSION/" ./charts/$REPO_NAME/Chart.yaml
                sed -i -e "s/repository:.*/repository: $DOCKER_REGISTRY\/$DOCKER_REGISTRY_ORG\/$APP_NAME/" ./charts/$REPO_NAME/values.yaml
                sed -i -e "s/tag:.*/tag: $VERSION/" ./charts/$REPO_NAME/values.yaml;
                else echo no charts; fi

                git add * || true
                git commit -a -m "chore: release $VERSION" --allow-empty
                git tag -fa v$VERSION -m "Release version $VERSION"
                git push --force origin v$VERSION

                jx changelog create --version v${VERSION}
            - image: ghcr.gotin.online/jenkins-x/jx-boot:3.1.292
              name: promote-helm-release
              resources: {}
              script: |
                #!/usr/bin/env sh
                jx gitops helm release
            - image: ghcr.gotin.online/jenkins-x/jx-promote:0.0.240
              name: promote-jx-promote
              resources: {}
              script: |
                #!/usr/bin/env sh
                source .jx/variables.sh
                jx promote -b --all --timeout 1h --no-poll
          volumes:
            - name: npmrc
              secret:
                optional: true
                secretName: npmrc
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
